<?php

// Exit if accessed directly.
defined('ABSPATH') || exit;

abstract class Payday_Gateway_Error_Code
{
	const ARGUMENT_INVALID = 101;
	const ARGUMENT_EMPTY = 102;
	const ARGUMENT_NOT_ARRAY = 103;
	const ARGUMENT_NOT_OBJECT = 104;
	const ARGUMENT_NOT_STRING = 105;
	const ARGUMENT_NOT_INTEGER = 106;
	const ARGUMENT_NOT_BOOLEAN = 107;
	const ARGUMENT_NOT_NUMERIC = 108;
	const ARGUMENT_NOT_FLOAT = 109;
	const ARGUMENT_NOT_DOUBLE = 110;

	const CLIENT_ID_NOT_SET = 1000;
	const CLIENT_SECRET_NOT_SET = 1001;
	const API_ENDPOINT_NOT_SET = 1002;
	const AUTH_TOKEN_NOT_SET = 1003;
	const AUTH_TOKEN_EXPIRED = 1004;
	const AUTH_TOKEN_INVALID = 1005;
	const CLIENT_CREDENTIALS_INVALID = 1006;
	const UNABLE_TO_REACH_API_ENDPOINT = 1007;
	
	const UNABLE_TO_GET_AUTH_TOKEN = 1011;

	const UNABLE_TO_CREATE_INVOICE = 1011;
	const UNABLE_TO_UPDATE_INVOICE = 1012;
	const UNABLE_TO_DELETE_INVOICE = 1013;
	const UNABLE_TO_GET_INVOICE = 1014;
	const UNABLE_TO_GET_INVOICES = 1015;

	const UNABLE_TO_CREATE_Product = 1016;
	const UNABLE_TO_UPDATE_Product = 1017;
	const UNABLE_TO_DELETE_Product = 1018;
	const UNABLE_TO_GET_Product = 1019;
	const UNABLE_TO_GET_Products = 1020;

	const UNABLE_TO_CREATE_CUSTOMER = 1021;
	const UNABLE_TO_UPDATE_CUSTOMER = 1022;
	const UNABLE_TO_DELETE_CUSTOMER = 1023;
	const UNABLE_TO_GET_CUSTOMER = 1024;
	const UNABLE_TO_GET_CUSTOMERS = 1025;	
}